server:
  port: 8080
spring:
  application:
    name: proxy
    loadbalancer:
      ribbon:
        enabled: false
  cloud:
    gateway:
      routes:
        - id: random_animal_route
          uri: lb://random-animal
          predicates:
            - Path=/random-animal/**
          filters:
            - StripPrefix=1
        - id: zoo_route
          uri: lb://zoo
          predicates:
            - Path=/zoo/**
          filters:
            - StripPrefix=1
eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org.springframework: debug

